### ISSUE TITLE
System to communicate an alert to users upon bp overhaul/refresh in a segment

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/djaopsp#124]
System editors should be able to create an alert for users if there is an update to one or more best practices in a segment that the user has completed an Assessment for. (Deb to provide more detailed guidance). 

This needs to be reviewed after and in alignment with the "Content creation protocol" (still to be developed).

**Comment by smirolo** [comment]
similar sort of alerts (but for assessment completed) is requested in #141.
