### ISSUE TITLE
"Download Self-assessment" & "Download Impr Plan": The spreadsheets should download in more 'formatted' form 

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/djaopsp#167]
Proposed formats: 
[Download Assessment_Format.xlsx](https://github.com/djaodjin/envconnect/files/1607490/Download.Assessment_Format.xlsx)
[Improvement Plan_Format(2).xlsx](https://github.com/djaodjin/envconnect/files/1607491/Improvement.Plan_Format.2.xlsx)

**Comment by smirolo** [comment]
openpyxl does not support insert of HTML-formatted text into worksheets. All sheets which are purely content should be printed into a PDF instead.

**Comment by smirolo** [comment]
Self-assessment spreadsheet and first page of improvement planning spreadsheet have been completed. Opening #194, #195 and closing this issue.

**Comment by deborabonner** [comment]
Formatting us faulty in top 3 rows of the downloaded spreadsheet.

**Comment by deborabonner** [comment]
**Assessment download:** 
1) Insert table lines and borders as shown in attachment
2)  insert definitions at the bottom of the table as shown in the attachment (with attention to same spacing)

**Planning download:**
1) Insert table lines and borders as shown in attachment
2)  create spacing and border around "Defintions" as shown in the attachment
