### ISSUE TITLE
Assessment buttons & toggle (see below)

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/djaopsp#205]
o	Reset: When a user clicks ‘Reset’, have a pop up window appear that reads: In the top bar, “Reset your assessment…”.  And then “Resetting your assessment will delete all answers in the current assessment. Do you wish to continue?    

o	Complete: Add an “s” to the word “improvement” in the textbox for the “Complete” button.

**Comment by smirolo** [comment]
User feedback: It isn't clear when hitting reset if it will reset only the current industry segment or all answers in all segments (current). It seems more natural to reset only at the industry segment.
