### ISSUE TITLE
Tutorial edits

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/djaopsp#263]
SCREEN SHOTS: 
Put a paragraph space or two between the screen shots used in a tutorial. Right now they looked squashed and uncomfortable, and they run into each other in a way that confuses the eye's ability to quickly identify an instruction with the screen. This would also make the minor size differences between a few of the screens unnoticeable. 

TUTORIAL WORDING:   
In the turorial, "Share results with customers, clients and investors",  delete the phrase "which may later be audited by clients/customers or investors" (first bullet point in the black box). Rationale: The point is better made in the "Share assessment..." screen. Putting it here draws unnecessary attention to the potential of being "audited", which is likely to scare users off. The "Share" is primarily to create a system of record.

**Comment by smirolo** [comment]
The tutorials page is in `templates/docs/tutorials.html`. A `TemplateView` url in urls.py might need to be added in order to view the page.
