### ISSUE TITLE
Assessment Nav: Download assessment

### ISSUE THREAD

**Issue by quiaro** [djaodjin/djaopsp#364]
<img width="535" alt="Screen Shot 2020-10-06 at 12 38 22" src="https://user-images.githubusercontent.com/311021/95246009-2083cd00-07d1-11eb-8cb6-ec577778af13.png">

**Comment by quiaro** [comment]
@smirolo for downloading I see the following in the demo app:

![image](https://user-images.githubusercontent.com/311021/95246329-8b350880-07d1-11eb-9b67-de2799f2be83.png)

Would you be able to confirm if this correct or if I should be making a different request? Thanks!

**Comment by smirolo** [comment]
It is correct.
