### ISSUE TITLE
Assessment Nav: Delete an assessment

### ISSUE THREAD

**Issue by quiaro** [djaodjin/djaopsp#365]
<img width="516" alt="Screen Shot 2020-10-06 at 12 38 54" src="https://user-images.githubusercontent.com/311021/95247453-1d89dc00-07d3-11eb-8094-ee853e0ab3e3.png">

**Comment by quiaro** [comment]
@smirolo what endpoint should I be calling for this?

**Comment by smirolo** [comment]
The [reset API](https://www.tspproject.org/docs/api/#CreateSampleReset)

**Comment by quiaro** [comment]
@smirolo the link you post seems outdated.
