### ISSUE TITLE
Improvement Plan: Integrate Filter Practice by Category dropdown with API

### ISSUE THREAD

**Issue by quiaro** [djaodjin/djaopsp#370]
![image](https://user-images.githubusercontent.com/311021/95262276-0b1a9d00-07e9-11eb-919a-a5503b6af752.png)

**Comment by smirolo** [comment]
I believe the Energy reduction, etc. are values inside the `tags` field in the [content API](https://www.tspproject.org/docs/api/#RetrievePageElementTree).

**Comment by quiaro** [comment]
> I believe the Energy reduction, etc. are values inside the `tags` field in the [content API](https://www.tspproject.org/docs/api/#RetrievePageElementTree).

Would you be able to provide a sample JSON for me to work on?

**Comment by smirolo** [comment]
Updated link to [content API](https://www.tspproject.org/docs/api/#RetrieveContentElementList).

You will see something like this in the `results` field:
```
{
      "path": "/construction/production/adjust-air-fuel-ratio",
      "title": "Adjust Air fuel ratio",
      "indent": 2,
      "environmental_value": 2,
      "business_value": 2,
      "profitability": 2,
      "implementation_ease": 2,
      "avg_value": 2,
      "tags":["Energy & Emissions"]
    }
```

The only 3 values possible for 'Category' are "Energy & Emissions",  "Waste" and "Water".

Side note: Energy and emissions are always combined here. There are no practices that apply to 2 categories at the same time in the current content, and I doubt there will either be.
