### ISSUE TITLE
Improvement Plan: Integrate Filter by Practice Category dropdown with API

### ISSUE THREAD

**Issue by quiaro** [djaodjin/djaopsp#371]
![image](https://user-images.githubusercontent.com/311021/95262412-52a12900-07e9-11eb-90d9-c615f7ba9be7.png)

**Comment by quiaro** [comment]
@smirolo What endpoint should I call to get these options?

**Comment by smirolo** [comment]
The options (environmental_value, business_value, etc.) are hard-coded. The intrinsic values of practices is available through the [content API](https://www.tspproject.org/docs/api/#RetrieveContentElementList). Is there filtering parameters on that API at this point? My guess is no.
