### ISSUE TITLE
Scorecard: Integrate score badge with API

### ISSUE THREAD

**Issue by quiaro** [djaodjin/djaopsp#384]
<img width="314" alt="Screen Shot 2020-10-07 at 22 59 20" src="https://user-images.githubusercontent.com/311021/95417199-a72fcb80-08f1-11eb-894e-308cfc9b38c1.png">

**Comment by quiaro** [comment]
@smirolo what endpoint would provide the UI with this information? Or how would it be calculated on the FE?

**Comment by smirolo** [comment]
This feature is part of the audit workflow. There will be some `audited` boolean field in the [response](https://www.tspproject.org/docs/api/#RetrieveBenchmark).
